package org.ngs.as3units.format
{
    import org.ngs.as3units.NonSI;
    import org.ngs.as3units.Prefix;
    import org.ngs.as3units.SI;
    import org.ngs.as3units.UCUM;
    
    public class DefaultUnitMetadata extends UnitMetadata
    {
        public function DefaultUnitMetadata () {
            
            // SI Units
            
            putProperty(SI.AMPERE, "NAME", "Ampere");
            putProperty(SI.CANDELA, "NAME", "Candela");
            putProperty(SI.KELVIN, "NAME", "Degree Kelvin");
            putProperty(SI.KILOGRAM, "NAME", "Kilogram");
            putProperty(SI.METRE, "NAME", "Meter");
            putProperty(SI.MOLE, "NAME", "Mole");
            putProperty(SI.SECOND, "NAME", "Second");
            putProperty(SI.GRAM, "NAME", "Gram");
            putProperty(SI.RADIAN, "NAME", "Radian");
            putProperty(SI.STERADIAN, "NAME", "Steradian");
            putProperty(SI.BIT, "NAME", "Bit");
            putProperty(SI.HERTZ, "NAME", "Hertz");
            putProperty(SI.NEWTON, "NAME", "Newton");
            putProperty(SI.PASCAL, "NAME", "Pascal");
            putProperty(SI.JOULE, "NAME", "Joule");
            putProperty(SI.WATT, "NAME", "Watt");
            putProperty(SI.COULOMB, "NAME", "Coulomb");
            putProperty(SI.VOLT, "NAME", "Volt");
            putProperty(SI.FARAD, "NAME", "Farad");
            putProperty(SI.OHM, "NAME", "Ohm");
            putProperty(SI.SIEMENS, "NAME", "Siemens");
            putProperty(SI.WEBER, "NAME", "Weber");
            putProperty(SI.TESLA, "NAME", "Tesla");
            putProperty(SI.HENRY, "NAME", "Henry");
            putProperty(SI.CELSIUS, "NAME", "Celsius");
            putProperty(SI.LUMEN, "NAME", "Lumen");
            putProperty(SI.LUX, "NAME", "Lux");
            putProperty(SI.BECQUEREL, "NAME", "Becquerel");
            putProperty(SI.GRAY, "NAME", "Gray");
            putProperty(SI.SIEVERT, "NAME", "Sievert");
            putProperty(SI.KATAL, "NAME", "Katal");
            putProperty(SI.METRES_PER_SECOND, "NAME", "Meters Per Second");
            putProperty(SI.METRES_PER_SQUARE_SECOND, "NAME", "Meters Per Second Per Second");
            putProperty(SI.SQUARE_METRE, "NAME", "Square Meter");
            putProperty(SI.CUBIC_METRE, "NAME", "Cubic Meter");
            putProperty(SI.KILOMETRE, "NAME", "Kilometer");
            putProperty(SI.CENTIMETRE, "NAME", "Centimeter");
            putProperty(SI.MILLIMETRE, "NAME", "Millimeter");
            
            putProperty(SI.AMPERE, "QUANTITY", "Electric Current");
            putProperty(SI.CANDELA, "QUANTITY", "Luminous Intensity");
            putProperty(SI.KELVIN, "QUANTITY", "Temperature");
            putProperty(SI.KILOGRAM, "QUANTITY", "Mass");
            putProperty(SI.METRE, "QUANTITY", "Length");
            putProperty(SI.METER, "QUANTITY", "Length");
            putProperty(SI.MOLE, "QUANTITY", "Amount Of Substance");
            putProperty(SI.SECOND, "QUANTITY", "Time");
            putProperty(SI.GRAM, "QUANTITY", "Mass");
            putProperty(SI.RADIAN, "QUANTITY", "Angle");
            putProperty(SI.STERADIAN, "QUANTITY", "Solid Angle");
            putProperty(SI.BIT, "QUANTITY", "Information");
            putProperty(SI.HERTZ, "QUANTITY", "Frequency");
            putProperty(SI.NEWTON, "QUANTITY", "Force");
            putProperty(SI.PASCAL, "QUANTITY", "Pressure");
            putProperty(SI.JOULE, "QUANTITY", "Energy");
            putProperty(SI.WATT, "QUANTITY", "Power");
            putProperty(SI.COULOMB, "QUANTITY", "Electric Charge");
            putProperty(SI.VOLT, "QUANTITY", "Electric Potential");
            putProperty(SI.FARAD, "QUANTITY", "Electric Capacitance");
            putProperty(SI.OHM, "QUANTITY", "Electric Resistance");
            putProperty(SI.SIEMENS, "QUANTITY", "Electric Conductance");
            putProperty(SI.WEBER, "QUANTITY", "Magnetic Flux");
            putProperty(SI.TESLA, "QUANTITY", "Magnetic Flux Density");
            putProperty(SI.HENRY, "QUANTITY", "Electric Inductance");
            putProperty(SI.CELSIUS, "QUANTITY", "Temperature");
            putProperty(SI.LUMEN, "QUANTITY", "Luminous Flux");
            putProperty(SI.LUX, "QUANTITY", "Illuminance");
            putProperty(SI.BECQUEREL, "QUANTITY", "Radioactive Activity");
            putProperty(SI.GRAY, "QUANTITY", "Absorbed Radiation Dose");
            putProperty(SI.SIEVERT, "QUANTITY", "Effective Radiation Dose");
            putProperty(SI.KATAL, "QUANTITY", "Catalytic Activity");
            putProperty(SI.METRES_PER_SECOND, "QUANTITY", "Velocity");
            putProperty(SI.METRES_PER_SQUARE_SECOND, "QUANTITY", "Acceleration");
            putProperty(SI.SQUARE_METRE, "QUANTITY", "Area");
            putProperty(SI.SQUARE_METER, "QUANTITY", "Area");
            putProperty(SI.CUBIC_METRE, "QUANTITY", "Volume");
            putProperty(SI.KILOMETRE, "QUANTITY", "Length");
            putProperty(SI.CENTIMETRE, "QUANTITY", "Length");
            putProperty(SI.MILLIMETRE, "QUANTITY", "Length");
            
            // Non-SI Units
            
            putProperty(NonSI.PERCENT, "NAME", "Percent");
            putProperty(NonSI.PER_MIL, "NAME", "Per Mille");
            putProperty(NonSI.DECIBEL, "NAME", "Decibel");
            putProperty(NonSI.ATOM, "NAME", "Atom");
            putProperty(NonSI.FOOT, "NAME", "Foot");
            putProperty(NonSI.FOOT_SURVEY_US, "NAME", "US Survey Foot");
            putProperty(NonSI.YARD, "NAME", "Yard");
            putProperty(NonSI.INCH, "NAME", "Inch");
            putProperty(NonSI.MILE, "NAME", "Mile");
            putProperty(NonSI.NAUTICAL_MILE, "NAME", "Nautical Mile");
            putProperty(NonSI.ANGSTROM, "NAME", "Angstrom");
            putProperty(NonSI.ASTRONOMICAL_UNIT, "NAME", "Astronomical Unit");
            putProperty(NonSI.LIGHT_YEAR, "NAME", "Light Year");
            putProperty(NonSI.PARSEC, "NAME", "Parsec");
            putProperty(NonSI.POINT, "NAME", "Point");
            putProperty(NonSI.PIXEL, "NAME", "Pixel");
            putProperty(NonSI.COMPUTER_POINT, "NAME", "Point");
            putProperty(NonSI.FOOT_MODIFIED_AMERICAN, "NAME", "Modified American Foot");
            putProperty(NonSI.FOOT_CLARKE, "NAME", "Clarke Foot");
            putProperty(NonSI.FOOT_INDIAN, "NAME", "Indian Foot");
            putProperty(NonSI.LINK, "NAME", "Link");
            putProperty(NonSI.LINK_BENOIT, "NAME", "Benoit Link");
            putProperty(NonSI.LINK_SEARS, "NAME", "Sears Link");
            putProperty(NonSI.CHAIN_BENOIT, "NAME", "Benoit Chain");
            putProperty(NonSI.CHAIN_SEARS, "NAME", "Sears Chain");
            putProperty(NonSI.YARD_SEARS, "NAME", "Sears Yard");
            putProperty(NonSI.YARD_INDIAN, "NAME", "Indian Yard");
            putProperty(NonSI.FATHOM, "NAME", "Fathom");
            putProperty(NonSI.MINUTE, "NAME", "Minute");
            putProperty(NonSI.HOUR, "NAME", "Hour");
            putProperty(NonSI.DAY, "NAME", "Day");
            putProperty(NonSI.WEEK, "NAME", "Week");
            putProperty(NonSI.YEAR, "NAME", "Year");
            putProperty(NonSI.MONTH, "NAME", "Month");
            putProperty(NonSI.DAY_SIDEREAL, "NAME", "Sidereal Day");
            putProperty(NonSI.YEAR_SIDEREAL, "NAME", "Sidereal Year");
            putProperty(NonSI.YEAR_CALENDAR, "NAME", "Calendar Year");
            putProperty(NonSI.MILLISECOND, "NAME", "Millisecond");
            putProperty(NonSI.ATOMIC_MASS, "NAME", "Atomic Mass");
            putProperty(NonSI.ELECTRON_MASS, "NAME", "Electron Mass");
            putProperty(NonSI.POUND, "NAME", "Pound");
            putProperty(NonSI.OUNCE, "NAME", "Ounce");
            putProperty(NonSI.TON_US, "NAME", "Ton US");
            putProperty(NonSI.TON_UK, "NAME", "Ton UK");
            putProperty(NonSI.METRIC_TON, "NAME", "Metric Ton");
            putProperty(NonSI.E, "NAME", "Electron Charge");
            putProperty(NonSI.FARADAY, "NAME", "Faraday");
            putProperty(NonSI.FRANKLIN, "NAME", "Franklin");
            putProperty(NonSI.RANKINE, "NAME", "Degree Rankine");
            putProperty(NonSI.FAHRENHEIT, "NAME", "Degree Fahrenheit");
            putProperty(NonSI.REVOLUTION, "NAME", "Revolution");
            putProperty(NonSI.DEGREE_ANGLE, "NAME", "Degree");
            putProperty(NonSI.MINUTE_ANGLE, "NAME", "Minute");
            putProperty(NonSI.SECOND_ANGLE, "NAME", "Second");
            putProperty(NonSI.CENTIRADIAN, "NAME", "Centiradian");
            putProperty(NonSI.GRADE, "NAME", "Grade");
            putProperty(NonSI.MILES_PER_HOUR, "NAME", "Miles Per Hour");
            putProperty(NonSI.KILOMETRES_PER_HOUR, "NAME", "Kilometers Per Hour");
            putProperty(NonSI.KNOT, "NAME", "Knot");
            putProperty(NonSI.MACH, "NAME", "Mach");
            putProperty(NonSI.C, "NAME", "Speed of Light");
            putProperty(NonSI.G, "NAME", "Acceleration of Gravity");
            putProperty(NonSI.ARE, "NAME", "Are");
            putProperty(NonSI.HECTARE, "NAME", "Hectare");
            putProperty(NonSI.SQUARE_KILOMETER, "NAME", "Square Kilometer");
            putProperty(NonSI.SQUARE_FOOT, "NAME", "Square Foot");
            putProperty(NonSI.ACRE, "NAME", "Acre");
            putProperty(NonSI.BYTE, "NAME", "Byte");
            putProperty(NonSI.OCTET, "NAME", "Octet");
            putProperty(NonSI.GILBERT, "NAME", "Gilbert");
            putProperty(NonSI.ERG, "NAME", "Erg");
            putProperty(NonSI.ELECTRON_VOLT, "NAME", "Electron Volt");
            putProperty(NonSI.LAMBERT, "NAME", "Lambert");
            putProperty(NonSI.MAXWELL, "NAME", "Maxwell");
            putProperty(NonSI.GAUSS, "NAME", "Gauss");
            putProperty(NonSI.DYNE, "NAME", "Dyne");
            putProperty(NonSI.KILOGRAM_FORCE, "NAME", "Kilogram");
            putProperty(NonSI.POUND_FORCE, "NAME", "Pound");
            putProperty(NonSI.HORSEPOWER, "NAME", "Horsepower");
            putProperty(NonSI.ATMOSPHERE, "NAME", "Atmosphere");
            putProperty(NonSI.BAR, "NAME", "Bar");
            putProperty(NonSI.MILLIMETER_OF_MERCURY, "NAME", "Millimeter of Mercury");
            putProperty(NonSI.INCH_OF_MERCURY, "NAME", "Inch of Mercury");
            putProperty(NonSI.RAD, "NAME", "Rad");
            putProperty(NonSI.REM, "NAME", "Rem");
            putProperty(NonSI.CURIE, "NAME", "Curie");
            putProperty(NonSI.RUTHERFORD, "NAME", "Rutherford");
            putProperty(NonSI.SPHERE, "NAME", "Sphere");
            putProperty(NonSI.LITRE, "NAME", "Liter");
            putProperty(NonSI.CUBIC_INCH, "NAME", "Cubic Inch");
            putProperty(NonSI.GALLON_LIQUID_US, "NAME", "Liquid Gallon US");
            putProperty(NonSI.OUNCE_LIQUID_US, "NAME", "Liquid Ounce US");
            putProperty(NonSI.GALLON_DRY_US, "NAME", "Dry Gallon US");
            putProperty(NonSI.GALLON_UK, "NAME", "Gallon UK");
            putProperty(NonSI.OUNCE_LIQUID_UK, "NAME", "Liquid Ounce UK");
            putProperty(NonSI.POISE, "NAME", "Poise");
            putProperty(NonSI.STOKE, "NAME", "Stroke");
            putProperty(NonSI.CFS, "NAME", "Cubic Foot per Second");
            putProperty(NonSI.ROENTGEN, "NAME", "Roentgen");
            
            putProperty(NonSI.PERCENT, "QUANTITY", "Dimensionless");
            putProperty(NonSI.PER_MIL, "QUANTITY", "Dimensionless");
            putProperty(NonSI.DECIBEL, "QUANTITY", "Dimensionless");
            putProperty(NonSI.ATOM, "QUANTITY", "Amount Of Substance");
            putProperty(NonSI.FOOT, "QUANTITY", "Length");
            putProperty(NonSI.FOOT_SURVEY_US, "QUANTITY", "Length");
            putProperty(NonSI.YARD, "QUANTITY", "Length");
            putProperty(NonSI.INCH, "QUANTITY", "Length");
            putProperty(NonSI.MILE, "QUANTITY", "Length");
            putProperty(NonSI.NAUTICAL_MILE, "QUANTITY", "Length");
            putProperty(NonSI.ANGSTROM, "QUANTITY", "Length");
            putProperty(NonSI.ASTRONOMICAL_UNIT, "QUANTITY", "Length");
            putProperty(NonSI.LIGHT_YEAR, "QUANTITY", "Length");
            putProperty(NonSI.PARSEC, "QUANTITY", "Length");
            putProperty(NonSI.POINT, "QUANTITY", "Length");
            putProperty(NonSI.PIXEL, "QUANTITY", "Length");
            putProperty(NonSI.COMPUTER_POINT, "QUANTITY", "Length");
            putProperty(NonSI.FOOT_MODIFIED_AMERICAN, "QUANTITY", "Length");
            putProperty(NonSI.FOOT_CLARKE, "QUANTITY", "Length");
            putProperty(NonSI.FOOT_INDIAN, "QUANTITY", "Length");
            putProperty(NonSI.LINK, "QUANTITY", "Length");
            putProperty(NonSI.LINK_BENOIT, "QUANTITY", "Length");
            putProperty(NonSI.LINK_SEARS, "QUANTITY", "Length");
            putProperty(NonSI.CHAIN_BENOIT, "QUANTITY", "Length");
            putProperty(NonSI.CHAIN_SEARS, "QUANTITY", "Length");
            putProperty(NonSI.YARD_SEARS, "QUANTITY", "Length");
            putProperty(NonSI.YARD_INDIAN, "QUANTITY", "Length");
            putProperty(NonSI.FATHOM, "QUANTITY", "Length");
            putProperty(NonSI.MINUTE, "QUANTITY", "Time");
            putProperty(NonSI.HOUR, "QUANTITY", "Time");
            putProperty(NonSI.DAY, "QUANTITY", "Time");
            putProperty(NonSI.WEEK, "QUANTITY", "Time");
            putProperty(NonSI.YEAR, "QUANTITY", "Time");
            putProperty(NonSI.MONTH, "QUANTITY", "Time");
            putProperty(NonSI.DAY_SIDEREAL, "QUANTITY", "Time");
            putProperty(NonSI.YEAR_SIDEREAL, "QUANTITY", "Time");
            putProperty(NonSI.YEAR_CALENDAR, "QUANTITY", "Time");
            putProperty(NonSI.MILLISECOND, "QUANTITY", "Time");
            putProperty(NonSI.ATOMIC_MASS, "QUANTITY", "Mass");
            putProperty(NonSI.ELECTRON_MASS, "QUANTITY", "Mass");
            putProperty(NonSI.POUND, "QUANTITY", "Mass");
            putProperty(NonSI.OUNCE, "QUANTITY", "Mass");
            putProperty(NonSI.TON_US, "QUANTITY", "Mass");
            putProperty(NonSI.TON_UK, "QUANTITY", "Mass");
            putProperty(NonSI.METRIC_TON, "QUANTITY", "Mass");
            putProperty(NonSI.E, "QUANTITY", "Electric Charge");
            putProperty(NonSI.FARADAY, "QUANTITY", "Electric Charge");
            putProperty(NonSI.FRANKLIN, "QUANTITY", "Electric Charge");
            putProperty(NonSI.RANKINE, "QUANTITY", "Temperature");
            putProperty(NonSI.FAHRENHEIT, "QUANTITY", "Temperature");
            putProperty(NonSI.REVOLUTION, "QUANTITY", "Angle");
            putProperty(NonSI.DEGREE_ANGLE, "QUANTITY", "Angle");
            putProperty(NonSI.MINUTE_ANGLE, "QUANTITY", "Angle");
            putProperty(NonSI.SECOND_ANGLE, "QUANTITY", "Angle");
            putProperty(NonSI.CENTIRADIAN, "QUANTITY", "Angle");
            putProperty(NonSI.GRADE, "QUANTITY", "Angle");
            putProperty(NonSI.MILES_PER_HOUR, "QUANTITY", "Velocity");
            putProperty(NonSI.KILOMETRES_PER_HOUR, "QUANTITY", "Velocity");
            putProperty(NonSI.KILOMETERS_PER_HOUR, "QUANTITY", "Velocity");
            putProperty(NonSI.KNOT, "QUANTITY", "Velocity");
            putProperty(NonSI.MACH, "QUANTITY", "Velocity");
            putProperty(NonSI.C, "QUANTITY", "Velocity");
            putProperty(NonSI.G, "QUANTITY", "Acceleration");
            putProperty(NonSI.ARE, "QUANTITY", "Area");
            putProperty(NonSI.HECTARE, "QUANTITY", "Area");
            putProperty(NonSI.SQUARE_KILOMETER, "QUANTITY", "Area");
            putProperty(NonSI.SQUARE_FOOT, "QUANTITY", "Area");
            putProperty(NonSI.ACRE, "QUANTITY", "Area");
            putProperty(NonSI.BYTE, "QUANTITY", "Information");
            putProperty(NonSI.OCTET, "QUANTITY", "Information");
            putProperty(NonSI.GILBERT, "QUANTITY", "Electric Current");
            putProperty(NonSI.ERG, "QUANTITY", "Energy");
            putProperty(NonSI.ELECTRON_VOLT, "QUANTITY", "Energy");
            putProperty(NonSI.LAMBERT, "QUANTITY", "Illuminance");
            putProperty(NonSI.MAXWELL, "QUANTITY", "Magnetic Flux");
            putProperty(NonSI.GAUSS, "QUANTITY", "Magnetic Flux Density");
            putProperty(NonSI.DYNE, "QUANTITY", "Force");
            putProperty(NonSI.KILOGRAM_FORCE, "QUANTITY", "Force");
            putProperty(NonSI.POUND_FORCE, "QUANTITY", "Force");
            putProperty(NonSI.HORSEPOWER, "QUANTITY", "Power");
            putProperty(NonSI.ATMOSPHERE, "QUANTITY", "Pressure");
            putProperty(NonSI.BAR, "QUANTITY", "Pressure");
            putProperty(NonSI.MILLIMETER_OF_MERCURY, "QUANTITY", "Pressure");
            putProperty(NonSI.INCH_OF_MERCURY, "QUANTITY", "Pressure");
            putProperty(NonSI.RAD, "QUANTITY", "Absorbed Radiation Dose");
            putProperty(NonSI.REM, "QUANTITY", "Absorbed Radiation Dose");
            putProperty(NonSI.CURIE, "QUANTITY", "Radioactive Activity");
            putProperty(NonSI.RUTHERFORD, "QUANTITY", "Radioactive Activity");
            putProperty(NonSI.SPHERE, "QUANTITY", "Solid Angle");
            putProperty(NonSI.LITRE, "QUANTITY", "Volume");
            putProperty(NonSI.LITER, "QUANTITY", "Volume");
            putProperty(NonSI.CUBIC_INCH, "QUANTITY", "Volume");
            putProperty(NonSI.GALLON_LIQUID_US, "QUANTITY", "Volume");
            putProperty(NonSI.OUNCE_LIQUID_US, "QUANTITY", "Volume");
            putProperty(NonSI.GALLON_DRY_US, "QUANTITY", "Volume");
            putProperty(NonSI.GALLON_UK, "QUANTITY", "Volume");
            putProperty(NonSI.OUNCE_LIQUID_UK, "QUANTITY", "Volume");
            putProperty(NonSI.POISE, "QUANTITY", "Dynamic Viscosity");
            putProperty(NonSI.STOKE, "QUANTITY", "Kinematic Viscosity");
            putProperty(NonSI.CFS, "QUANTITY", "Volumetric Flow Rate");
            putProperty(NonSI.ROENTGEN, "QUANTITY", "Ion Dose");
            
            // UCUM units
            
            putProperty(UCUM.METER, "NAME", "Meter");
            putProperty(UCUM.SECOND, "NAME", "Second");
            putProperty(UCUM.GRAM, "NAME", "Gram");
            putProperty(UCUM.RADIAN, "NAME", "Radian");
            putProperty(UCUM.KELVIN, "NAME", "Kelvin");
            putProperty(UCUM.COULOMB, "NAME", "Coulomb");
            putProperty(UCUM.CANDELA, "NAME", "Candela");
            putProperty(UCUM.TRIILLIONS, "NAME", "Trillions");
            putProperty(UCUM.BILLIONS, "NAME", "Billions");
            putProperty(UCUM.MILLIONS, "NAME", "Millions");
            putProperty(UCUM.THOUSANDS, "NAME", "Thousands");
            putProperty(UCUM.HUNDREDS, "NAME", "Hundreds");
            putProperty(UCUM.PI, "NAME", "Pi");
            putProperty(UCUM.PERCENT, "NAME", "Percent");
            putProperty(UCUM.PER_THOUSAND, "NAME", "Per Thousand");
            putProperty(UCUM.PER_MILLION, "NAME", "Per Million");
            putProperty(UCUM.PER_BILLION, "NAME", "Per Billion");
            putProperty(UCUM.PER_TRILLION, "NAME", "Per Trillion");
            putProperty(UCUM.MOLE, "NAME", "Mole");
            putProperty(UCUM.STERADIAN, "NAME", "Steradian");
            putProperty(UCUM.HERTZ, "NAME", "Hertz");
            putProperty(UCUM.NEWTON, "NAME", "Newton");
            putProperty(UCUM.PASCAL, "NAME", "Pascal");
            putProperty(UCUM.JOULE, "NAME", "Joule");
            putProperty(UCUM.WATT, "NAME", "Watt");
            putProperty(UCUM.AMPERE, "NAME", "Ampere");
            putProperty(UCUM.VOLT, "NAME", "Volt");
            putProperty(UCUM.FARAD, "NAME", "Farad");
            putProperty(UCUM.OHM, "NAME", "Ohm");
            putProperty(UCUM.SIEMENS, "NAME", "Siemens");
            putProperty(UCUM.WEBER, "NAME", "Weber");
            putProperty(UCUM.CELSIUS, "NAME", "Celsius");
            putProperty(UCUM.TESLA, "NAME", "Tesla");
            putProperty(UCUM.HENRY, "NAME", "Henry");
            putProperty(UCUM.LUMEN, "NAME", "Lumen");
            putProperty(UCUM.LUX, "NAME", "Lux");
            putProperty(UCUM.BECQUEREL, "NAME", "Becquerel");
            putProperty(UCUM.GRAY, "NAME", "Gray");
            putProperty(UCUM.SIEVERT, "NAME", "Sievert");
            putProperty(UCUM.DEGREE, "NAME", "Degree");
            putProperty(UCUM.GRADE, "NAME", "Grade");
            putProperty(UCUM.MINUTE_ANGLE, "NAME", "Minute");
            putProperty(UCUM.SECOND_ANGLE, "NAME", "Second");
            putProperty(UCUM.LITER, "NAME", "Liter");
            putProperty(UCUM.ARE, "NAME", "Are");
            putProperty(UCUM.MINUTE, "NAME", "Minute");
            putProperty(UCUM.HOUR, "NAME", "Hour");
            putProperty(UCUM.DAY, "NAME", "Day");
            putProperty(UCUM.YEAR_TROPICAL, "NAME", "Year (tropical)");
            putProperty(UCUM.YEAR_JULIAN, "NAME", "Year (Julian)");
            putProperty(UCUM.YEAR_GREGORIAN, "NAME", "Year (Gregorian)");
            putProperty(UCUM.YEAR, "NAME", "Year");
            putProperty(UCUM.WEEK, "NAME", "Week");
            putProperty(UCUM.MONTH_SYNODAL, "NAME", "Month (synodal)");
            putProperty(UCUM.MONTH_JULIAN, "NAME", "Month (Julian)");
            putProperty(UCUM.MONTH_GREGORIAN, "NAME", "Month (Gregorian)");
            putProperty(UCUM.MONTH, "NAME", "Month");
            putProperty(UCUM.TONNE, "NAME", "Tonne");
            putProperty(UCUM.BAR, "NAME", "Bar");
            putProperty(UCUM.ATOMIC_MASS_UNIT, "NAME", "Atomic Mass Unit");
            putProperty(UCUM.ELECTRON_VOLT, "NAME", "Electron Volt");
            putProperty(UCUM.ASTRONOMIC_UNIT, "NAME", "Astronomic Unit");
            putProperty(UCUM.PARSEC, "NAME", "Parsec");
            putProperty(UCUM.C, "NAME", "C (speed of light)");
            putProperty(UCUM.PLANCK, "NAME", "Planck");
            putProperty(UCUM.BOLTZMAN, "NAME", "Boltzman");
            putProperty(UCUM.PERMITTIVITY_OF_VACUUM, "NAME", "Permittivity of Vacuum");
            putProperty(UCUM.PERMEABILITY_OF_VACUUM, "NAME", "Permeability of Vacuum");
            putProperty(UCUM.ELEMENTARY_CHARGE, "NAME", "Elementary Charge");
            putProperty(UCUM.ELECTRON_MASS, "NAME", "Electron Mass");
            putProperty(UCUM.PROTON_MASS, "NAME", "Proton Mass");
            putProperty(UCUM.NEWTON_CONSTANT_OF_GRAVITY, "NAME", "Gravitational Constant");
            putProperty(UCUM.ACCELLERATION_OF_FREEFALL, "NAME", "Accelleration of Freefall");
            putProperty(UCUM.ATMOSPHERE, "NAME", "Atmosphere");
            putProperty(UCUM.LIGHT_YEAR, "NAME", "Light Year");
            putProperty(UCUM.GRAM_FORCE, "NAME", "Gram Force");
            putProperty(UCUM.KAYSER, "NAME", "Kayser");
            putProperty(UCUM.GAL, "NAME", "Gal");
            putProperty(UCUM.DYNE, "NAME", "Dyne");
            putProperty(UCUM.ERG, "NAME", "Erg");
            putProperty(UCUM.POISE, "NAME", "Poise");
            putProperty(UCUM.BIOT, "NAME", "Biot");
            putProperty(UCUM.STOKES, "NAME", "Stokes");
            putProperty(UCUM.MAXWELL, "NAME", "Maxwell");
            putProperty(UCUM.GAUSS, "NAME", "Gauss");
            putProperty(UCUM.OERSTED, "NAME", "Oersted");
            putProperty(UCUM.GILBERT, "NAME", "Gilbert");
            putProperty(UCUM.STILB, "NAME", "Stilb");
            putProperty(UCUM.LAMBERT, "NAME", "Lambert");
            putProperty(UCUM.PHOT, "NAME", "Phot");
            putProperty(UCUM.CURIE, "NAME", "Curie");
            putProperty(UCUM.ROENTGEN, "NAME", "Roentgen");
            putProperty(UCUM.RAD, "NAME", "Rad");
            putProperty(UCUM.REM, "NAME", "Rem");
            putProperty(UCUM.INCH_INTERNATIONAL, "NAME", "International Inch");
            putProperty(UCUM.FOOT_INTERNATIONAL, "NAME", "International Foot");
            putProperty(UCUM.YARD_INTERNATIONAL, "NAME", "International Yard");
            putProperty(UCUM.MILE_INTERNATIONAL, "NAME", "International Mile");
            putProperty(UCUM.FATHOM_INTERNATIONAL, "NAME", "International Fathom");
            putProperty(UCUM.NAUTICAL_MILE_INTERNATIONAL, "NAME", "International Nautical Mile");
            putProperty(UCUM.KNOT_INTERNATIONAL, "NAME", "International Knot");
            putProperty(UCUM.SQUARE_INCH_INTERNATIONAL, "NAME", "International Square Inch");
            putProperty(UCUM.SQUARE_FOOT_INTERNATIONAL, "NAME", "International Square Foot");
            putProperty(UCUM.SQUARE_YARD_INTERNATIONAL, "NAME", "International Square Yard");
            putProperty(UCUM.CUBIC_INCH_INTERNATIONAL, "NAME", "International Cubic Inch");
            putProperty(UCUM.CUBIC_FOOT_INTERNATIONAL, "NAME", "International Cubic Foot");
            putProperty(UCUM.CUBIC_YARD_INTERNATIONAL, "NAME", "International Cubic Yard");
            putProperty(UCUM.BOARD_FOOT_INTERNATIONAL, "NAME", "International Board Foot");
            putProperty(UCUM.CORD_INTERNATIONAL, "NAME", "International Cord");
            putProperty(UCUM.MIL_INTERNATIONAL, "NAME", "International Mil");
            putProperty(UCUM.CIRCULAR_MIL_INTERNATIONAL, "NAME", "International Circular Mil");
            putProperty(UCUM.HAND_INTERNATIONAL, "NAME", "International Hand");
            putProperty(UCUM.FOOT_US_SURVEY, "NAME", "US Survey Foot");
            putProperty(UCUM.YARD_US_SURVEY, "NAME", "US Survey Yard");
            putProperty(UCUM.INCH_US_SURVEY, "NAME", "US Survey Inch");
            putProperty(UCUM.ROD_US_SURVEY, "NAME", "US Survey Rod");
            putProperty(UCUM.CHAIN_US_SURVEY, "NAME", "US Survey Chain");
            putProperty(UCUM.LINK_US_SURVEY, "NAME", "US Survey Link");
            putProperty(UCUM.RAMDEN_CHAIN_US_SURVEY, "NAME", "US Survey Ramden Chain");
            putProperty(UCUM.RAMDEN_LINK_US_SURVEY, "NAME", "US Survey Ramden Link");
            putProperty(UCUM.FATHOM_US_SURVEY, "NAME", "US Survey Fathom");
            putProperty(UCUM.FURLONG_US_SURVEY, "NAME", "US Survey Furlong");
            putProperty(UCUM.MILE_US_SURVEY, "NAME", "US Survey Mile");
            putProperty(UCUM.ACRE_US_SURVEY, "NAME", "US Survey Acre");
            putProperty(UCUM.SQUARE_ROD_US_SURVEY, "NAME", "US Survey Square Rod");
            putProperty(UCUM.SQUARE_MILE_US_SURVEY, "NAME", "US Survey Square Mile");
            putProperty(UCUM.SECTION_US_SURVEY, "NAME", "US Survey Section");
            putProperty(UCUM.TOWNSHP_US_SURVEY, "NAME", "US Survey Township");
            putProperty(UCUM.MIL_US_SURVEY, "NAME", "US Survey Mil");
            putProperty(UCUM.INCH_BRITISH, "NAME", "British Inch");
            putProperty(UCUM.FOOT_BRITISH, "NAME", "British Foot");
            putProperty(UCUM.ROD_BRITISH, "NAME", "British Rod");
            putProperty(UCUM.CHAIN_BRITISH, "NAME", "British Chain");
            putProperty(UCUM.LINK_BRITISH, "NAME", "British Link");
            putProperty(UCUM.FATHOM_BRITISH, "NAME", "British Fathom");
            putProperty(UCUM.PACE_BRITISH, "NAME", "British Pace");
            putProperty(UCUM.YARD_BRITISH, "NAME", "British Yard");
            putProperty(UCUM.MILE_BRITISH, "NAME", "British Mile");
            putProperty(UCUM.NAUTICAL_MILE_BRITISH, "NAME", "British Nautical Mile");
            putProperty(UCUM.KNOT_BRITISH, "NAME", "British Knot");
            putProperty(UCUM.ACRE_BRITISH, "NAME", "British Acre");
            putProperty(UCUM.GALLON_US, "NAME", "US Gallon");
            putProperty(UCUM.BARREL_US, "NAME", "US Barrel");
            putProperty(UCUM.QUART_US, "NAME", "US Quart");
            putProperty(UCUM.PINT_US, "NAME", "US Pint");
            putProperty(UCUM.GILL_US, "NAME", "US Gill");
            putProperty(UCUM.FLUID_OUNCE_US, "NAME", "US Fluid Ounce");
            putProperty(UCUM.FLUID_DRAM_US, "NAME", "US Fulid Dram");
            putProperty(UCUM.MINIM_US, "NAME", "US Minim");
            putProperty(UCUM.CORD_US, "NAME", "US Cord");
            putProperty(UCUM.BUSHEL_US, "NAME", "US Bushel");
            putProperty(UCUM.GALLON_WINCHESTER, "NAME", "Winchester Gallon");
            putProperty(UCUM.PECK_US, "NAME", "US Peck");
            putProperty(UCUM.DRY_QUART_US, "NAME", "US Dry Quart");
            putProperty(UCUM.DRY_PINT_US, "NAME", "US Dry Pint");
            putProperty(UCUM.TABLESPOON_US, "NAME", "US Tablespoon");
            putProperty(UCUM.TEASPOON_US, "NAME", "US Teaspoon");
            putProperty(UCUM.CUP_US, "NAME", "US Cup");
            putProperty(UCUM.GALLON_BRITISH, "NAME", "British Gallon");
            putProperty(UCUM.PECK_BRITISH, "NAME", "British Peck");
            putProperty(UCUM.BUSHEL_BRITISH, "NAME", "British Bushel");
            putProperty(UCUM.QUART_BRITISH, "NAME", "British Quart");
            putProperty(UCUM.PINT_BRITISH, "NAME", "British Pint");
            putProperty(UCUM.GILL_BRITISH, "NAME", "British Gil");
            putProperty(UCUM.FLUID_OUNCE_BRITISH, "NAME", "British Fluid Ounce");
            putProperty(UCUM.FLUID_DRAM_BRITISH, "NAME", "British Fluid Dram");
            putProperty(UCUM.MINIM_BRITISH, "NAME", "British Minim");
            putProperty(UCUM.GRAIN, "NAME", "Grain");
            putProperty(UCUM.POUND, "NAME", "Pound");
            putProperty(UCUM.OUNCE, "NAME", "Ounce");
            putProperty(UCUM.DRAM, "NAME", "Dram");
            putProperty(UCUM.SHORT_HUNDREDWEIGHT, "NAME", "Short Hundredweight");
            putProperty(UCUM.LONG_HUNDREDWEIGHT, "NAME", "Long Hundredweight");
            putProperty(UCUM.SHORT_TON, "NAME", "Short Ton");
            putProperty(UCUM.LONG_TON, "NAME", "Long Ton");
            putProperty(UCUM.STONE, "NAME", "Stone");
            putProperty(UCUM.POUND_FORCE, "NAME", "Pound Force");
            putProperty(UCUM.PENNYWEIGHT_TROY, "NAME", "Troy Pennyweight");
            putProperty(UCUM.OUNCE_TROY, "NAME", "Troy Ounce");
            putProperty(UCUM.POUND_TROY, "NAME", "Troy Pound");
            putProperty(UCUM.SCRUPLE_APOTHECARY, "NAME", "Apothecary Scruple");
            putProperty(UCUM.DRAM_APOTHECARY, "NAME", "Apothecary Dram");
            putProperty(UCUM.OUNCE_APOTHECARY, "NAME", "Apothecary Ounce");
            putProperty(UCUM.POUND_APOTHECARY, "NAME", "Apothecary Pound");
            putProperty(UCUM.LINE, "NAME", "Line");
            putProperty(UCUM.POINT, "NAME", "Point");
            putProperty(UCUM.PICA, "NAME", "Pica");
            putProperty(UCUM.POINT_PRINTER, "NAME", "Printer Point");
            putProperty(UCUM.PICA_PRINTER, "NAME", "Printer Pica");
            putProperty(UCUM.PIED, "NAME", "Pied");
            putProperty(UCUM.POUCE, "NAME", "Pouce");
            putProperty(UCUM.LINGE, "NAME", "Linge");
            putProperty(UCUM.DIDOT, "NAME", "Didot");
            putProperty(UCUM.CICERO, "NAME", "Cicero");
            putProperty(UCUM.FAHRENHEIT, "NAME", "Degrees Fahrenheit");
            putProperty(UCUM.CALORIE_AT_15C, "NAME", "Calorie at 15\u00B0C");
            putProperty(UCUM.CALORIE_AT_20C, "NAME", "Calorie at 20\u00B0C");
            putProperty(UCUM.CALORIE_MEAN, "NAME", "Calorie Mean");
            putProperty(UCUM.CALORIE_INTERNATIONAL_TABLE, "NAME", "International Table Calorie");
            putProperty(UCUM.CALORIE_THERMOCHEMICAL, "NAME", "Thermochemical Calorie");
            putProperty(UCUM.CALORIE, "NAME", "Calorie");
            putProperty(UCUM.CALORIE_FOOD, "NAME", "Food Calorie");
            putProperty(UCUM.BTU_AT_39F, "NAME", "BTU at 39\u00B0F");
            putProperty(UCUM.BTU_AT_59F, "NAME", "BTU at 59\u00B0F");
            putProperty(UCUM.BTU_AT_60F, "NAME", "BTU at 60\u00B0F");
            putProperty(UCUM.BTU_MEAN, "NAME", "BTU Mean");
            putProperty(UCUM.BTU_INTERNATIONAL_TABLE, "NAME", "International Table BTU");
            putProperty(UCUM.BTU_THERMOCHEMICAL, "NAME", "Thermochemical BTU");
            putProperty(UCUM.BTU, "NAME", "BTU");
            putProperty(UCUM.HORSEPOWER, "NAME", "Horsepower");
            putProperty(UCUM.STERE, "NAME", "Stere");
            putProperty(UCUM.ANGSTROM, "NAME", "Angstrom");
            putProperty(UCUM.BARN, "NAME", "Barn");
            putProperty(UCUM.ATMOSPHERE_TECHNICAL, "NAME", "Atmosphere (techinical)");
            putProperty(UCUM.MHO, "NAME", "Mho");
            putProperty(UCUM.POUND_PER_SQUARE_INCH, "NAME", "Pound Per Square Inch");
            putProperty(UCUM.CIRCLE, "NAME", "Circle");
            putProperty(UCUM.SPHERE, "NAME", "Sphere");
            putProperty(UCUM.CARAT_METRIC, "NAME", "Carat Metric");
            putProperty(UCUM.CARAT_GOLD, "NAME", "Carat Gold");
            putProperty(UCUM.BIT, "NAME", "Bit");
            putProperty(UCUM.BYTE, "NAME", "Byte");
            putProperty(UCUM.BAUD, "NAME", "Baud");
            
            
            putProperty(UCUM.METER, "QUANTITY", "Length");
            putProperty(UCUM.SECOND, "QUANTITY", "Time");
            putProperty(UCUM.GRAM, "QUANTITY", "Mass");
            putProperty(UCUM.KILOGRAM, "QUANTITY", "Mass");
            putProperty(UCUM.RADIAN, "QUANTITY", "Angle");
            putProperty(UCUM.KELVIN, "QUANTITY", "Temperature");
            putProperty(UCUM.COULOMB, "QUANTITY", "Electric Charge");
            putProperty(UCUM.CANDELA, "QUANTITY", "Luminous Intensity");
            putProperty(UCUM.TRIILLIONS, "QUANTITY", "Dimensionless");
            putProperty(UCUM.BILLIONS, "QUANTITY", "Dimensionless");
            putProperty(UCUM.MILLIONS, "QUANTITY", "Dimensionless");
            putProperty(UCUM.THOUSANDS, "QUANTITY", "Dimensionless");
            putProperty(UCUM.HUNDREDS, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PI, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PERCENT, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PER_THOUSAND, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PER_MILLION, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PER_BILLION, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PER_TRILLION, "QUANTITY", "Dimensionless");
            putProperty(UCUM.MOLE, "QUANTITY", "Amount OfSubstance");
            putProperty(UCUM.STERADIAN, "QUANTITY", "Solid Angle");
            putProperty(UCUM.HERTZ, "QUANTITY", "Frequency");
            putProperty(UCUM.NEWTON, "QUANTITY", "Force");
            putProperty(UCUM.PASCAL, "QUANTITY", "Pressure");
            putProperty(UCUM.JOULE, "QUANTITY", "Energy");
            putProperty(UCUM.WATT, "QUANTITY", "Power");
            putProperty(UCUM.AMPERE, "QUANTITY", "Electric Current");
            putProperty(UCUM.VOLT, "QUANTITY", "Electric Potential");
            putProperty(UCUM.FARAD, "QUANTITY", "Electric Capacitance");
            putProperty(UCUM.OHM, "QUANTITY", "Electric Resistance");
            putProperty(UCUM.SIEMENS, "QUANTITY", "Electric Conductance");
            putProperty(UCUM.WEBER, "QUANTITY", "Magnetic Flux");
            putProperty(UCUM.CELSIUS, "QUANTITY", "Temperature");
            putProperty(UCUM.TESLA, "QUANTITY", "Magnetic Flux Density");
            putProperty(UCUM.HENRY, "QUANTITY", "Electric Inductance");
            putProperty(UCUM.LUMEN, "QUANTITY", "Luminous Flux");
            putProperty(UCUM.LUX, "QUANTITY", "Luminous Intensity");
            putProperty(UCUM.BECQUEREL, "QUANTITY", "Radioactive Activity");
            putProperty(UCUM.GRAY, "QUANTITY", "Absorbed Radiation Dose");
            putProperty(UCUM.SIEVERT, "QUANTITY", "Effective Radiation Dose");
            putProperty(UCUM.DEGREE, "QUANTITY", "Angle");
            putProperty(UCUM.GRADE, "QUANTITY", "Angle");
            putProperty(UCUM.GON, "QUANTITY", "Angle");
            putProperty(UCUM.MINUTE_ANGLE, "QUANTITY", "Angle");
            putProperty(UCUM.SECOND_ANGLE, "QUANTITY", "Angle");
            putProperty(UCUM.LITER, "QUANTITY", "Volume");
            putProperty(UCUM.ARE, "QUANTITY", "Area");
            putProperty(UCUM.MINUTE, "QUANTITY", "Time");
            putProperty(UCUM.HOUR, "QUANTITY", "Time");
            putProperty(UCUM.DAY, "QUANTITY", "Time");
            putProperty(UCUM.YEAR_TROPICAL, "QUANTITY", "Time");
            putProperty(UCUM.YEAR_JULIAN, "QUANTITY", "Time");
            putProperty(UCUM.YEAR_GREGORIAN, "QUANTITY", "Time");
            putProperty(UCUM.YEAR, "QUANTITY", "Time");
            putProperty(UCUM.WEEK, "QUANTITY", "Time");
            putProperty(UCUM.MONTH_SYNODAL, "QUANTITY", "Time");
            putProperty(UCUM.MONTH_JULIAN, "QUANTITY", "Time");
            putProperty(UCUM.MONTH_GREGORIAN, "QUANTITY", "Time");
            putProperty(UCUM.MONTH, "QUANTITY", "Time");
            putProperty(UCUM.TONNE, "QUANTITY", "Mass");
            putProperty(UCUM.BAR, "QUANTITY", "Pressure");
            putProperty(UCUM.ATOMIC_MASS_UNIT, "QUANTITY", "Mass");
            putProperty(UCUM.ELECTRON_VOLT, "QUANTITY", "Energy");
            putProperty(UCUM.ASTRONOMIC_UNIT, "QUANTITY", "Length");
            putProperty(UCUM.PARSEC, "QUANTITY", "Length");
            putProperty(UCUM.C, "QUANTITY", "Velocity");
            putProperty(UCUM.PLANCK, "QUANTITY", "Action");
            putProperty(UCUM.BOLTZMAN, "QUANTITY", "Dimensionless");
            putProperty(UCUM.PERMITTIVITY_OF_VACUUM, "QUANTITY", "Electric Permittivity");
            putProperty(UCUM.PERMEABILITY_OF_VACUUM, "QUANTITY", "Magnetic Permittivity");
            putProperty(UCUM.ELEMENTARY_CHARGE, "QUANTITY", "Electric Charge");
            putProperty(UCUM.ELECTRON_MASS, "QUANTITY", "Mass");
            putProperty(UCUM.PROTON_MASS, "QUANTITY", "Mass");
            putProperty(UCUM.NEWTON_CONSTANT_OF_GRAVITY, "QUANTITY", "Acceleration");
            putProperty(UCUM.ACCELLERATION_OF_FREEFALL, "QUANTITY", "Acceleration");
            putProperty(UCUM.ATMOSPHERE, "QUANTITY", "Pressure");
            putProperty(UCUM.LIGHT_YEAR, "QUANTITY", "Length");
            putProperty(UCUM.GRAM_FORCE, "QUANTITY", "Force");
            putProperty(UCUM.KAYSER, "QUANTITY", "Lineic Number");
            putProperty(UCUM.GAL, "QUANTITY", "Acceleration");
            putProperty(UCUM.DYNE, "QUANTITY", "Force");
            putProperty(UCUM.ERG, "QUANTITY", "Energy");
            putProperty(UCUM.POISE, "QUANTITY", "Dynamic Viscosity");
            putProperty(UCUM.BIOT, "QUANTITY", "Electric Current");
            putProperty(UCUM.STOKES, "QUANTITY", "Kinematic Viscosity");
            putProperty(UCUM.MAXWELL, "QUANTITY", "Magnetic Flux");
            putProperty(UCUM.GAUSS, "QUANTITY", "Magnetic Flux Density");
            putProperty(UCUM.OERSTED, "QUANTITY", "Magnetic Flux Intensity");
            putProperty(UCUM.GILBERT, "QUANTITY", "Magnetic Tension");
            putProperty(UCUM.STILB, "QUANTITY", "Luminous Intensity Density");
            putProperty(UCUM.LAMBERT, "QUANTITY", "Illuminance");
            putProperty(UCUM.PHOT, "QUANTITY", "Illuminance");
            putProperty(UCUM.CURIE, "QUANTITY", "Radioactive Activity");
            putProperty(UCUM.ROENTGEN, "QUANTITY", "Ion Dose");
            putProperty(UCUM.RAD, "QUANTITY", "Absorbed Radiation Dose");
            putProperty(UCUM.REM, "QUANTITY", "Effective Radiation Dose");
            putProperty(UCUM.INCH_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.FOOT_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.YARD_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.MILE_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.FATHOM_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.NAUTICAL_MILE_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.KNOT_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.SQUARE_INCH_INTERNATIONAL, "QUANTITY", "Area");
            putProperty(UCUM.SQUARE_FOOT_INTERNATIONAL, "QUANTITY", "Area");
            putProperty(UCUM.SQUARE_YARD_INTERNATIONAL, "QUANTITY", "Area");
            putProperty(UCUM.CUBIC_INCH_INTERNATIONAL, "QUANTITY", "Volume");
            putProperty(UCUM.CUBIC_FOOT_INTERNATIONAL, "QUANTITY", "Volume");
            putProperty(UCUM.CUBIC_YARD_INTERNATIONAL, "QUANTITY", "Volume");
            putProperty(UCUM.BOARD_FOOT_INTERNATIONAL, "QUANTITY", "Volume");
            putProperty(UCUM.CORD_INTERNATIONAL, "QUANTITY", "Volume");
            putProperty(UCUM.MIL_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.CIRCULAR_MIL_INTERNATIONAL, "QUANTITY", "Area");
            putProperty(UCUM.HAND_INTERNATIONAL, "QUANTITY", "Length");
            putProperty(UCUM.FOOT_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.YARD_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.INCH_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.ROD_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.CHAIN_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.LINK_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.RAMDEN_CHAIN_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.RAMDEN_LINK_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.FATHOM_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.FURLONG_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.MILE_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.ACRE_US_SURVEY, "QUANTITY", "Area");
            putProperty(UCUM.SQUARE_ROD_US_SURVEY, "QUANTITY", "Area");
            putProperty(UCUM.SQUARE_MILE_US_SURVEY, "QUANTITY", "Area");
            putProperty(UCUM.SECTION_US_SURVEY, "QUANTITY", "Area");
            putProperty(UCUM.TOWNSHP_US_SURVEY, "QUANTITY", "Area");
            putProperty(UCUM.MIL_US_SURVEY, "QUANTITY", "Length");
            putProperty(UCUM.INCH_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.FOOT_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.ROD_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.CHAIN_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.LINK_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.FATHOM_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.PACE_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.YARD_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.MILE_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.NAUTICAL_MILE_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.KNOT_BRITISH, "QUANTITY", "Length");
            putProperty(UCUM.ACRE_BRITISH, "QUANTITY", "Area");
            putProperty(UCUM.GALLON_US, "QUANTITY", "Volume");
            putProperty(UCUM.BARREL_US, "QUANTITY", "Volume");
            putProperty(UCUM.QUART_US, "QUANTITY", "Volume");
            putProperty(UCUM.PINT_US, "QUANTITY", "Volume");
            putProperty(UCUM.GILL_US, "QUANTITY", "Volume");
            putProperty(UCUM.FLUID_OUNCE_US, "QUANTITY", "Volume");
            putProperty(UCUM.FLUID_DRAM_US, "QUANTITY", "Volume");
            putProperty(UCUM.MINIM_US, "QUANTITY", "Volume");
            putProperty(UCUM.CORD_US, "QUANTITY", "Volume");
            putProperty(UCUM.BUSHEL_US, "QUANTITY", "Volume");
            putProperty(UCUM.GALLON_WINCHESTER, "QUANTITY", "Volume");
            putProperty(UCUM.PECK_US, "QUANTITY", "Volume");
            putProperty(UCUM.DRY_QUART_US, "QUANTITY", "Volume");
            putProperty(UCUM.DRY_PINT_US, "QUANTITY", "Volume");
            putProperty(UCUM.TABLESPOON_US, "QUANTITY", "Volume");
            putProperty(UCUM.TEASPOON_US, "QUANTITY", "Volume");
            putProperty(UCUM.CUP_US, "QUANTITY", "Volume");
            putProperty(UCUM.GALLON_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.PECK_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.BUSHEL_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.QUART_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.PINT_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.GILL_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.FLUID_OUNCE_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.FLUID_DRAM_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.MINIM_BRITISH, "QUANTITY", "Volume");
            putProperty(UCUM.GRAIN, "QUANTITY", "Mass");
            putProperty(UCUM.POUND, "QUANTITY", "Mass");
            putProperty(UCUM.OUNCE, "QUANTITY", "Mass");
            putProperty(UCUM.DRAM, "QUANTITY", "Mass");
            putProperty(UCUM.SHORT_HUNDREDWEIGHT, "QUANTITY", "Mass");
            putProperty(UCUM.LONG_HUNDREDWEIGHT, "QUANTITY", "Mass");
            putProperty(UCUM.SHORT_TON, "QUANTITY", "Mass");
            putProperty(UCUM.LONG_TON, "QUANTITY", "Mass");
            putProperty(UCUM.STONE, "QUANTITY", "Mass");
            putProperty(UCUM.POUND_FORCE, "QUANTITY", "Force");
            putProperty(UCUM.PENNYWEIGHT_TROY, "QUANTITY", "Mass");
            putProperty(UCUM.OUNCE_TROY, "QUANTITY", "Mass");
            putProperty(UCUM.POUND_TROY, "QUANTITY", "Mass");
            putProperty(UCUM.SCRUPLE_APOTHECARY, "QUANTITY", "Mass");
            putProperty(UCUM.DRAM_APOTHECARY, "QUANTITY", "Mass");
            putProperty(UCUM.OUNCE_APOTHECARY, "QUANTITY", "Mass");
            putProperty(UCUM.POUND_APOTHECARY, "QUANTITY", "Mass");
            putProperty(UCUM.LINE, "QUANTITY", "Length");
            putProperty(UCUM.POINT, "QUANTITY", "Length");
            putProperty(UCUM.PICA, "QUANTITY", "Length");
            putProperty(UCUM.POINT_PRINTER, "QUANTITY", "Length");
            putProperty(UCUM.PICA_PRINTER, "QUANTITY", "Length");
            putProperty(UCUM.PIED, "QUANTITY", "Length");
            putProperty(UCUM.POUCE, "QUANTITY", "Length");
            putProperty(UCUM.LINGE, "QUANTITY", "Length");
            putProperty(UCUM.DIDOT, "QUANTITY", "Length");
            putProperty(UCUM.CICERO, "QUANTITY", "Length");
            putProperty(UCUM.FAHRENHEIT, "QUANTITY", "Temperature");
            putProperty(UCUM.CALORIE_AT_15C, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE_AT_20C, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE_MEAN, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE_INTERNATIONAL_TABLE, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE_THERMOCHEMICAL, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE, "QUANTITY", "Energy");
            putProperty(UCUM.CALORIE_FOOD, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_AT_39F, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_AT_59F, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_AT_60F, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_MEAN, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_INTERNATIONAL_TABLE, "QUANTITY", "Energy");
            putProperty(UCUM.BTU_THERMOCHEMICAL, "QUANTITY", "Energy");
            putProperty(UCUM.BTU, "QUANTITY", "Energy");
            putProperty(UCUM.HORSEPOWER, "QUANTITY", "Power");
            putProperty(UCUM.STERE, "QUANTITY", "Volume");
            putProperty(UCUM.ANGSTROM, "QUANTITY", "Length");
            putProperty(UCUM.BARN, "QUANTITY", "Area");
            putProperty(UCUM.ATMOSPHERE_TECHNICAL, "QUANTITY", "Pressure");
            putProperty(UCUM.MHO, "QUANTITY", "Electric Conductance");
            putProperty(UCUM.POUND_PER_SQUARE_INCH, "QUANTITY", "Pressure");
            putProperty(UCUM.CIRCLE, "QUANTITY", "Pressure");
            putProperty(UCUM.SPHERE, "QUANTITY", "Pressure");
            putProperty(UCUM.CARAT_METRIC, "QUANTITY", "Mass");
            putProperty(UCUM.CARAT_GOLD, "QUANTITY", "Dimensionless");
            putProperty(UCUM.BIT, "QUANTITY", "Information");
            putProperty(UCUM.BYTE, "QUANTITY", "Information");
            putProperty(UCUM.BAUD, "QUANTITY", "Information Rate");
        }
    }
}
